# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - build

variables:

  ### Variables ###
  serviceNamespace: $(SERVICE_NAMESPACE)
  serviceName: frontend

pool:
  vmImage: ubuntu-latest

stages:

  #### Deploy Image Stage ####
  - stage: Deploy_Image
    jobs:
      - job: Deploy_Image
        steps:
        - task: Kubernetes@1
          displayName: 'Deploying $(serviceName) Image...'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'olympus'
            namespace: $(serviceNamespace)
            command: 'apply'
            arguments: '-f kubernetes-manifests/$(serviceName).yaml'