# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:

  ### Variables ###
  serviceNamespace: $(SERVICE_NAMESPACE)
  serviceName: $(SERVICE_NAME)

pool:
  vmImage: ubuntu-latest

stages:

  #### Build Image Stage ####
  - stage: Redeploy_Image
    jobs:
      - job: Redeploy_Image
        steps:
        - task: KubernetesManifest@0
          displayName: Patch
          inputs: 
            action: patch
            kind: deployment
            name: $(serviceName)
            mergeStrategy: strategic
            # patch: '{"spec":{"containers":[{"name":"demo","image":"foobar/demo:2239"}]}}'
            patch: '{"spec":{"template":{"metadata":{"labels":{"redeploy":"$(Build.BuildNumber)"}}}}}'
            kubernetesServiceConnection: 'olympus'
            namespace: $(serviceNamespace)